language: go
go: 1.9
services:
- docker

script:
  - make builddocker

deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file: bin
    skip_cleanup: true
    file_glob: true
    on:
      tags: true
