language: go
go: 1.9
services:
- docker

script:
  - make builddocker
  - TAG=${TRAVIS_TAG} make releases

deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    files:
      - ${TRAVIS_TAG}.linux.tar.gz
      - ${TRAVIS_TAG}.windows.tar.gz
      - ${TRAVIS_TAG}.darwin.tar.gz
    on:
      tags: true
